import { useHackyHideButton } from '@/hooks/use-hacky-hide-button'
import { DashboardLayout } from '@/layouts/dashboard'
import { NavigationProvider } from '@/providers/navigation'
import '@/styles/index.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  useHackyHideButton()

  return (
    <>
      <Head>
        <title>Side Navigation Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationProvider>
        <DashboardLayout>
          <Component {...pageProps} />
        </DashboardLayout>
      </NavigationProvider>
    </>
  )
}
