import { TopNav } from "@/components/top-nav";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Persistent Side Navigation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
      <main>Main area</main>
    </>
  );
}
